version: "3.3"
name: nougat
services:
  server:
    build:
      context: .
    container_name: nougat-api-srver
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    environment:
      - HOST_PORT=8503
      - CONTAINER_PORT=8503
      - NOUGAT_CHECKPOINT=/app/models/small
      - NOUGAT_BATCH_SIZE=4
    image: nougat-api-server
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    stdin_open: true
    tty: true
    volumes:
      - ./models:/app/models
      - ./pdfs:/app/pdfs